RooftopAcademy/rooftend

- src/categories/categories.entity.ts
- src/categories/categories/controllers/categories.controller.ts
- src/categories/categories/services/categories.service.ts
Not linked issue
Swagger:
- Categories entity
- Categories controller
> Feature categories documentation

- src/favorites/controllers/favorites.controller.ts
- Cambiado: `@ApiTags('favorites')` => `@ApiTags('Favorites')`
> Capitalized ApiTags 'favorites'

- src/review/controllers/review.controller.ts
- src/review/review.entity.ts
**Arreglados varios errores respecto a reviews**
- Cambiar el `ApiTag` de "reviews" a "Reviews"
- Cambiar el atributo `id` a `readonly` en la documentación
- Ocultar los atributos `entityId` y `entityType` en la documentación y en las respuestas
> Fix reviews

- src/account-status/controllers/account-status.controller.ts
- src/account-status/models/account-status.dto.ts
- src/account-status/models/account-status.interface.ts
- src/account-status/services/account-status.service.ts
Se agrego un DTO en vez de la interface.
Se mejoro la documentacion de la entity y el controlador.
POST
DELETE and PATCH: returns forbidden
> Inprove status acc documentation

- src/payment-methods/controllers/payment-method.controller.spec.ts
- src/payment-methods/controllers/payment-method.controller.ts
- src/payment-methods/models/create-payment-method.dto.ts
- src/payment-methods/models/payment-method.entity.ts
- src/payment-methods/services/payment-method.service.spec.ts
#137 
- Changed logic when returning values in payment-methods.controller.ts
- Added testing for payment methods controller
- Added testing for payment methods service
- Modified schema example in find method ( Get(':id') ).
- Added models folder to wrap dto and entity.
**payment-method.controller.spec.ts**
**payment-method.service.spec.ts**
> Feature add payment methods testing

- src/saved-items/controllers/saved-items.controller.ts
- src/saved-items/saved-items.module.ts
- src/saved-items/services/saved-items.service.ts
> fixed route imports

- src/answers/answers.module.ts
- src/answers/controllers/answers.controller.ts
- src/answers/entities/answer.dto.ts
- src/answers/entities/answer.entity.ts
- src/answers/services/answers.service.ts
- src/app.module.ts
Created module for answers.
Implemented POST and SOFTDELETE
Added documentation in swagger
#149 
**Future feature: Create test for module**
POST:
DELETE
> Feature answer module

- src/favorites/controllers/favorites.controller.ts
- src/favorites/services/favorites.service.ts
Se cambio la query en SQL a query builder.
> modified SQL query =to=> query builder

- src/addresses/entities/address.entity.ts
- src/cart-item/entities/cart-item.entity.ts
- src/cart/entities/cart.entity.ts
- src/custom-messages/entities/custom-messages.entity.ts
- src/deliveries/entities/delivery.entity.ts
- src/favorites/entities/favorite.entity.ts
- src/history/models/history.entity.ts
- src/items/entities/items.entity.ts
- src/offers/entities/offer.entity.ts
- src/payment-methods/models/payment-method.entity.ts
- src/payments/entities/payment.entity.ts
- src/photos/models/photos.entity.ts
- src/platform/entities/platform.entity.ts
- src/platform/entities/update-platform-dto.entity.ts
- src/questions/entities/question.entity.ts
- src/search/entities/search.entity.ts
- src/stores/entities/stores.entity.ts
- src/support/entities/supportCategory.entity.ts
- src/support/entities/supportQuestion.entity.ts
- src/support/entities/supportRequest.entity.ts
- Replaced ```'CURRENT_TIMESTAMP'``` by ```() => 'CURRENT_TIMESTAMP'``` in all occurrences.
> Fixed default dates.

- src/authentication/controllers/authentication.controller.ts
- src/users/entities/log-in-user-dto.entity.ts
> Auth documentation

- src/cart-item/services/cart-item.service.ts
- src/phones/services/phones.service.ts
- src/review/controllers/review.controller.ts
- tsconfig.json
Closes #219 
Se solucionaron algunos errores que hacian que la aplicacion no compilase
> Fix refactor

- src/cart/services/cart.service.ts
- src/phones/services/phones.service.ts
- src/review/controllers/review.controller.ts
- tsconfig.json
4 files changes to let the project running
> "Hotfix the main"

- src/authentication/controllers/authentication.controller.ts
- src/authentication/services/authentication.service.ts
> Create new service method for registry controller

- src/users/controllers/user.controller.ts
- src/users/entities/edit-password-dto.entity.ts
- src/users/entities/user.entity.ts
- src/users/services/user.service.ts
#199 
- Refactor user controller: deleted Post endpoint, added Patch endpoints for edit username, email and password, edited Delete endpoint.
- Refactor user service according to controller changes.
- Created DTO to edit password.
- Modified deletedAt example and removed unique properties. 
**Endpoints**
**Register**
**GET endpoint**
**GET endpoint / username**
**GET endpoint / email**
**GET endpoint / password**
> Feature user refactor

- src/authentication/controllers/authentication.controller.spec.ts
- src/authentication/controllers/authentication.controller.ts
- src/authentication/services/authentication.service.ts
- src/authentication/strategies/local.strategy.ts
- src/users/entities/user.entity.ts
- src/users/services/user.service.ts
- Refactor in authentication module.
- Fix authentication testing
> 2022 01 17 refactor auth

- src/authentication/controllers/authentication.controller.ts
- src/authentication/services/authentication.service.ts
- Added try catch for not valid token
- Removed console.log
- Removed account status from user
> 2022 01 19 refactor auth add mail

- src/message-post-purchases/entities/message-post-purchase.entity.ts
> Changed @Column decorator for @CreateDateColumn

- src/cart-item/entities/cart-item.entity.ts
- src/cart/entities/cart.entity.ts
Se arreglaron las relaciones de cart y cartItem que estaban mal hechas. Se tiparon correctamente las entidades y se dejaron los ids con el decorador `@RelationId` con propositos de compatibilidad.
> fix cart relations

- src/authentication/services/authentication.service.ts
- src/cart/services/cart.service.ts
No linked issue
- Created new event for user confirmed to create a new cart.
- Fixed bug in cart create method when passing user id. 
Peer coding with @Marcosl14
> Refactor user registration

- src/authentication/controllers/authentication.controller.spec.ts
- src/authentication/services/authentication.service.spec.ts
> 2022 01 22 re testing authentication

- src/account-status/controllers/account-status.controller.ts
Se removieron comentarios, imports inecesarios
> Remove unnecessary methods account status
